### ISSUE TITLE
allow users to run normally without root

### ISSUE THREAD

**Issue by jonorthwash** [SwatPhonLab/UltraTrace#121]
Currently to run the script normally `install.sh` seems to require sudo.  Users should be able to run install `UltraTrace.py` into a user bin directory, or even just run it in situ.

**Comment by keggsmurph21** [comment]
Just to clarify, you're talking about [`install.sh`](https://github.com/SwatPhonLab/UltraTrace/blob/master/install.sh), not [`bin/install`](https://github.com/SwatPhonLab/UltraTrace/blob/master/bin/install), right?  For the record, `bin/install` is basically deprecated at this point in favor of a `pip`-installable architecture.

Regarding `install.sh`: all this script does is install system-level dependencies.  It's not possible to install these sorts of dependencies without root access.  Without these libraries, some of the functionality won't work.  I agree that we should ultimately support a limited-functionality version if the user does not have these libraries AND does not have permissions to install them on their system.

I can add a patch for that in the next few days.

**Comment by keggsmurph21** [comment]
Implemented in dfa0c6d.  I'll leave this for you to close in case you had other concerns :^)

**Comment by jonorthwash** [comment]
> Regarding `install.sh`: all this script does is install system-level dependencies.

Ah, I thought this was for putting the "executable" in `$PATH`.  How is this done?

What I had in mind here was in regards to running the program.  Now I'm using `bin/ultratrace/ultratrace`, which works without putting it in path, but it might be nice if there were a symlink or wrapper script in the root directory of the repo.

**Comment by jonorthwash** [comment]
> I agree that we should ultimately support a limited-functionality version if the user does not have these libraries AND does not have permissions to install them on their system.

I thought we already supported not loading UltraTrace modules that had uninstalled dependencies?

**Comment by jonorthwash** [comment]
> For the record, `bin/install` is basically deprecated at this point in favor of a `pip`-installable architecture.

It would be really nice to be able to install (and keep maintained) dependencies with apt or brew or equivalent.

**Comment by keggsmurph21** [comment]
> Ah, I thought this was for putting the "executable" in `$PATH`. How is this done?
> 
> What I had in mind here was in regards to running the program. Now I'm using `bin/ultratrace/ultratrace`, which works without putting it in path, but it might be nice if there were a symlink or wrapper script in the root directory of the repo.

Eventually (i.e., in the next few weeks), we'd like to publish this module to `PyPI`, and then users would be able to `pip install ultratrace` and automatically<sup>*</sup> get `ultratrace` on their `$PATH`.

Right now, it is possible to change the install location, although it requires manually editing the `bin/install` script [here](https://github.com/SwatPhonLab/UltraTrace/blob/e295eec5a7a5697a52a4124feb47cb4873c52b97/bin/install#L21).

> I thought we already supported not loading UltraTrace modules that had uninstalled dependencies?

We theoretically support that, but we don't, for example, handle the case where the user doesn't have `pydicom` installed at the moment.  I just am not confident that our current method of checking the `*_LIBS_INSTALLED` variables is used reliably enough.
```bash
$ mkvirtualenv tmp
$ pip install numpy  # also required
$ python -m ultratrace
Traceback (most recent call last):
  File "/usr/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/kevinmurphy/src/swatphonlab/ultratrace/ultratrace/__main__.py", line 4, in <module>
    from . import modules
  File "/home/kevinmurphy/src/swatphonlab/ultratrace/ultratrace/modules/__init__.py", line 2, in <module>
    from .dicom import Dicom
  File "/home/kevinmurphy/src/swatphonlab/ultratrace/ultratrace/modules/dicom.py", line 4, in <module>
    from ..util.framereader import ULTScanLineReader, DicomReader, DicomPNGReader, LABEL_TO_READER, READERS
  File "/home/kevinmurphy/src/swatphonlab/ultratrace/ultratrace/util/framereader.py", line 7, in <module>
    import pydicom as dicom
ModuleNotFoundError: No module named 'pydicom'
```

>It would be really nice to be able to install (and keep maintained) dependencies with apt or brew or equivalent.

I agree this would be really nice.  This is probably something to think of for after our most recent upcoming deadline.

<sup>*</sup> Assuming normal python installation and such.

**Comment by jonorthwash** [comment]
> Eventually (i.e., in the next few weeks), we'd like to publish this module to `PyPI`, and then users would be able to `pip install ultratrace` and automatically* get `ultratrace` on their `$PATH`.

I have no objections to this plan, but this is not great for developers.  I guess we'll want to continue running it however works best for development and bypass pip.

**Comment by jonorthwash** [comment]
> I just am not confident that our current method of checking the `*_LIBS_INSTALLED` variables is used reliably enough.

Yeah, this is almost certainly true.

**Comment by jonorthwash** [comment]
> This is probably something to think of for after our most recent upcoming deadline.

+1

**Comment by mr-martian** [comment]
> > I just am not confident that our current method of checking the `*_LIBS_INSTALLED` variables is used reliably enough.
> 
> Yeah, this is almost certainly true.

I can confirm that none of my code uses it.

**Comment by qiyoulu** [comment]
Is this still something to work on?

**Comment by jonorthwash** [comment]
I'm not sure.  I think we need to figure out what current best practices for install/setup scripts are (probably nothing like what we're currently doing) and go with that.

**Comment by qiyoulu** [comment]
I'm trying to set up Docker - that way users can run the app without root.

**Comment by jonorthwash** [comment]
The problem this issue reports isn't running UltraTrace, but installing it.

Also, access to Docker on a system usually requires root, or special access of some sort.

I think the best way to address installation issues is to pare down the dependencies to things easily installed in user space.  There are also ways of packaging python dependencies with an executable.

I also don't see this issue as high-priority, at least not compared to others.

**Comment by qiyoulu** [comment]
In that case we can try something like PyInstaller or PyOxidizer that packages all the dependencies with the program, so the user doesn't have to install anything separately.

And yeah, this should be worked on when the UI rewrite is pretty much done.
