### ISSUE TITLE
issues on Windows

### ISSUE THREAD

**Issue by jonorthwash** [SwatPhonLab/UltraTrace#136]
- [x] Most keyboard shortcuts seem ineffective.
- [x] No playback (probably need to install ffmpeg).
- [x] A bunch of errors on the command line.

Full trace of me piddling around with it:
```
C:\Users\Jonathan\Documents\UltraTrace>python -m ultratrace
C:\Users\Jonathan\AppData\Local\Programs\Python\Python38\lib\site-packages\pydub-0.23.1-py3.8.egg\pydub\utils.py:165: RuntimeWarning: Couldn't find ffmpeg or avconv - defaulting to ffmpeg, but may not work
  warn("Couldn't find ffmpeg or avconv - defaulting to ffmpeg, but may not work", RuntimeWarning)
INFO:   initializing UltraTrace
INFO:    - initializing module: Data
DEBUG:     - parsing directory: `Z:/ultrasound-data-example`
DEBUG:     - creating new metadata file: `Z:/ultrasound-data-example\metadata.json`
INFO:    - initializing module: Control
INFO:    - initializing module: Trace
INFO:    - initializing module: Dicom
INFO:    - initializing module: Audio
INFO:    - initializing module: Video
C:\Users\Jonathan\AppData\Local\Programs\Python\Python38\lib\site-packages\pydub-0.23.1-py3.8.egg\pydub\utils.py:193: RuntimeWarning: Couldn't find ffprobe or avprobe - defaulting to ffprobe, but may not work
  warn("Couldn't find ffprobe or avprobe - defaulting to ffprobe, but may not work", RuntimeWarning)
ERROR:  Unable to load audio file: `Z:\ultrasound-data-example\20150629171639.flac` [WinError 2] The system cannot find the file specified
INFO:    - initializing module: TextGrid
ERROR:  '_tkinter.tkapp' object has no attribute 'Spectrogram'
INFO:    - initializing module: Spectrogram
INFO:    - loading widgets
ERROR:  Unable to load audio file: `Z:\ultrasound-data-example\20150629171639.flac` [WinError 2] The system cannot find the file specified
DEBUG:  DicomImgReader: reading dicom
DEBUG:  DicomImgReader: copying pixels
DEBUG:  DicomImgReader: dumping pixels
Exception in Tkinter callback
Traceback (most recent call last):
  File "C:\Users\Jonathan\AppData\Local\Programs\Python\Python38\lib\tkinter\__init__.py", line 1883, in __call__
    return self.func(*args)
  File "C:\Users\Jonathan\Documents\UltraTrace\ultratrace\modules\textgrid.py", line 501, in getBounds
    z_out = (a-(a/f))/2
TypeError: unsupported operand type(s) for /: 'float' and 'decimal.Decimal'
Exception in Tkinter callback
Traceback (most recent call last):
  File "C:\Users\Jonathan\AppData\Local\Programs\Python\Python38\lib\tkinter\__init__.py", line 1883, in __call__
    return self.func(*args)
  File "C:\Users\Jonathan\Documents\UltraTrace\ultratrace\modules\textgrid.py", line 501, in getBounds
    z_out = (a-(a/f))/2
TypeError: unsupported operand type(s) for /: 'float' and 'decimal.Decimal'
Exception in Tkinter callback
Traceback (most recent call last):
  File "C:\Users\Jonathan\AppData\Local\Programs\Python\Python38\lib\tkinter\__init__.py", line 1883, in __call__
    return self.func(*args)
  File "C:\Users\Jonathan\Documents\UltraTrace\ultratrace\modules\textgrid.py", line 501, in getBounds
    z_out = (a-(a/f))/2
TypeError: unsupported operand type(s) for /: 'float' and 'decimal.Decimal'
Exception in Tkinter callback
Traceback (most recent call last):
  File "C:\Users\Jonathan\AppData\Local\Programs\Python\Python38\lib\tkinter\__init__.py", line 1883, in __call__
    return self.func(*args)
  File "C:\Users\Jonathan\Documents\UltraTrace\ultratrace\modules\textgrid.py", line 501, in getBounds
    z_out = (a-(a/f))/2
TypeError: unsupported operand type(s) for /: 'float' and 'decimal.Decimal'
Exception in Tkinter callback
Traceback (most recent call last):
  File "C:\Users\Jonathan\AppData\Local\Programs\Python\Python38\lib\tkinter\__init__.py", line 1883, in __call__
    return self.func(*args)
  File "C:\Users\Jonathan\Documents\UltraTrace\ultratrace\modules\textgrid.py", line 501, in getBounds
    z_out = (a-(a/f))/2
TypeError: unsupported operand type(s) for /: 'float' and 'decimal.Decimal'
Exception in Tkinter callback
Traceback (most recent call last):
  File "C:\Users\Jonathan\AppData\Local\Programs\Python\Python38\lib\tkinter\__init__.py", line 1883, in __call__
    return self.func(*args)
  File "C:\Users\Jonathan\Documents\UltraTrace\ultratrace\modules\textgrid.py", line 501, in getBounds
    z_out = (a-(a/f))/2
TypeError: unsupported operand type(s) for /: 'float' and 'decimal.Decimal'
Exception in Tkinter callback
Traceback (most recent call last):
  File "C:\Users\Jonathan\AppData\Local\Programs\Python\Python38\lib\tkinter\__init__.py", line 1883, in __call__
    return self.func(*args)
  File "C:\Users\Jonathan\Documents\UltraTrace\ultratrace\modules\textgrid.py", line 501, in getBounds
    z_out = (a-(a/f))/2
TypeError: unsupported operand type(s) for /: 'float' and 'decimal.Decimal'
Exception in Tkinter callback
Traceback (most recent call last):
  File "C:\Users\Jonathan\AppData\Local\Programs\Python\Python38\lib\tkinter\__init__.py", line 1883, in __call__
    return self.func(*args)
  File "C:\Users\Jonathan\Documents\UltraTrace\ultratrace\modules\textgrid.py", line 387, in changeIntervals
    duration = decimal.Decimal(self.end) - self.start
TypeError: unsupported operand type(s) for -: 'decimal.Decimal' and 'float'
Exception in Tkinter callback
Traceback (most recent call last):
  File "C:\Users\Jonathan\AppData\Local\Programs\Python\Python38\lib\tkinter\__init__.py", line 1883, in __call__
    return self.func(*args)
  File "C:\Users\Jonathan\Documents\UltraTrace\ultratrace\modules\playback.py", line 123, in playpauseAV
    self.readyAudio(start, end)
  File "C:\Users\Jonathan\Documents\UltraTrace\ultratrace\modules\playback.py", line 149, in readyAudio
    extrasecs = extrafs/self.sfile.frame_rate
AttributeError: 'NoneType' object has no attribute 'frame_rate'
Exception in Tkinter callback
Traceback (most recent call last):
  File "C:\Users\Jonathan\AppData\Local\Programs\Python\Python38\lib\tkinter\__init__.py", line 1883, in __call__
    return self.func(*args)
  File "C:\Users\Jonathan\Documents\UltraTrace\ultratrace\modules\playback.py", line 123, in playpauseAV
    self.readyAudio(start, end)
  File "C:\Users\Jonathan\Documents\UltraTrace\ultratrace\modules\playback.py", line 149, in readyAudio
    extrasecs = extrafs/self.sfile.frame_rate
AttributeError: 'NoneType' object has no attribute 'frame_rate'
Exception in Tkinter callback
Traceback (most recent call last):
  File "C:\Users\Jonathan\AppData\Local\Programs\Python\Python38\lib\tkinter\__init__.py", line 1883, in __call__
    return self.func(*args)
  File "C:\Users\Jonathan\Documents\UltraTrace\ultratrace\modules\playback.py", line 123, in playpauseAV
    self.readyAudio(start, end)
  File "C:\Users\Jonathan\Documents\UltraTrace\ultratrace\modules\playback.py", line 149, in readyAudio
    extrasecs = extrafs/self.sfile.frame_rate
AttributeError: 'NoneType' object has no attribute 'frame_rate'
Exception in Tkinter callback
Traceback (most recent call last):
  File "C:\Users\Jonathan\AppData\Local\Programs\Python\Python38\lib\tkinter\__init__.py", line 1883, in __call__
    return self.func(*args)
  File "C:\Users\Jonathan\Documents\UltraTrace\ultratrace\modules\playback.py", line 123, in playpauseAV
    self.readyAudio(start, end)
  File "C:\Users\Jonathan\Documents\UltraTrace\ultratrace\modules\playback.py", line 149, in readyAudio
    extrasecs = extrafs/self.sfile.frame_rate
AttributeError: 'NoneType' object has no attribute 'frame_rate'
Exception in Tkinter callback
Traceback (most recent call last):
  File "C:\Users\Jonathan\AppData\Local\Programs\Python\Python38\lib\tkinter\__init__.py", line 1883, in __call__
    return self.func(*args)
  File "C:\Users\Jonathan\Documents\UltraTrace\ultratrace\modules\playback.py", line 123, in playpauseAV
    self.readyAudio(start, end)
  File "C:\Users\Jonathan\Documents\UltraTrace\ultratrace\modules\playback.py", line 149, in readyAudio
    extrasecs = extrafs/self.sfile.frame_rate
AttributeError: 'NoneType' object has no attribute 'frame_rate'
```

**Comment by jonorthwash** [comment]
The errors on the command line and possibly the keyboard shortcuts appear to have been #141.

**Comment by jonorthwash** [comment]
> The errors on the command line and possibly the keyboard shortcuts appear to have been #141.

Yep, this all works now.  I was running python 3.8.0 on the Windows machine.

**Comment by jonorthwash** [comment]
Playback works after installing ffmpeg and putting the path in environment variables per [these instructions](https://windowsloop.com/install-ffmpeg-windows-10/).
