### ISSUE TITLE
problem with spectrogram?

### ISSUE THREAD

**Issue by jonorthwash** [SwatPhonLab/UltraTrace#144]
I seem to not be getting a spectrogram for most (all?) recordings.  There's no related error in the logs until this:

```
ERROR:  '_tkinter.tkapp' object has no attribute 'Spectrogram'
```

**Comment by jonorthwash** [comment]
```python
>>> import parselmouth
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.8/dist-packages/parselmouth/__init__.py", line 22, in <module>
    from parselmouth.base import Parselmouth
  File "/usr/local/lib/python3.8/dist-packages/parselmouth/base.py", line 30, in <module>
    from parselmouth.adapters.dfp.interface import DFPInterface
  File "/usr/local/lib/python3.8/dist-packages/parselmouth/adapters/dfp/interface.py", line 17, in <module>
    from urllib import quote
ImportError: cannot import name 'quote' from 'urllib' (/usr/lib/python3.8/urllib/__init__.py)
```

**Comment by jonorthwash** [comment]
Okay, so you can't have `paselmouth` installed, and need `praat-parselmouth` instead.
