### ISSUE TITLE
Can't build praat-parselmouth module on Linux

### ISSUE THREAD

**Issue by qiyoulu** [SwatPhonLab/UltraTrace#170]
```
bash
$ pip install praat-parselmouth
[…]
$       [1418/1428] Building CXX object praat/CMakeFiles/praat.dir/dwtools/praat_David_init.cpp.o
      ninja: build stopped: subcommand failed.
        File "/tmp/pip-build-env-6cqk0kov/overlay/lib/python3.11/site-packages/skbuild/setuptools_wrap.py", line 593, in setup
          cmkr.make(make_args, env=env)
        File "/tmp/pip-build-env-6cqk0kov/overlay/lib/python3.11/site-packages/skbuild/cmaker.py", line 504, in make
          raise SKBuildError(
      
      
      --------------------------------------------------------------------------------
      -- Trying "Ninja" generator
      --------------------------------
      ---------------------------
      ----------------------
      -----------------
      ------------
      -------
      --
      --
      -------
      ------------
      -----------------
      ----------------------
      ---------------------------
      --------------------------------
      -- Trying "Ninja" generator - success
      --------------------------------------------------------------------------------
      
      Configuring Project
        Working directory:
          /tmp/pip-install-in9yi450/praat-parselmouth_ae57548160114c17b06d5d9d37323c9c/_skbuild/linux-x86_64-3.11/cmake-build
        Command:
          cmake /tmp/pip-install-in9yi450/praat-parselmouth_ae57548160114c17b06d5d9d37323c9c -G Ninja -DCMAKE_INSTALL_PREFIX:PATH=/tmp/pip-install-in9yi450/praat-parselmouth_ae57548160114c17b06d5d9d37323c9c/_skbuild/linux-x86_64-3.11/cmake-install/src -DPYTHON_EXECUTABLE:FILEPATH=/usr/bin/python3 -DPYTHON_VERSION_STRING:STRING=3.11.0rc1 -DPYTHON_INCLUDE_DIR:PATH=/usr/include/python3.11 -DPYTHON_LIBRARY:FILEPATH=/usr/lib64/libpython3.11.so -DSKBUILD:INTERNAL=TRUE -DCMAKE_MODULE_PATH:PATH=/tmp/pip-build-env-6cqk0kov/overlay/lib/python3.11/site-packages/skbuild/resources/cmake -DCMAKE_BUILD_TYPE:STRING=Release
      
      Traceback (most recent call last):
      
      An error occurred while building with CMake.
        Command:
          cmake --build . --target install --config Release --
        Source directory:
          /tmp/pip-install-in9yi450/praat-parselmouth_ae57548160114c17b06d5d9d37323c9c
        Working directory:
          /tmp/pip-install-in9yi450/praat-parselmouth_ae57548160114c17b06d5d9d37323c9c/_skbuild/linux-x86_64-3.11/cmake-build
      Please see CMake's output for more information.
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for praat-parselmouth
Failed to build praat-parselmouth
ERROR: Could not build wheels for praat-parselmouth, which is required to install pyproject.toml-based projects
```

**Comment by qiyoulu** [comment]
This was on Fedora Linux 37. Will try on Ubuntu.

**Comment by mr-martian** [comment]
The relevant place for this is probably actually on https://github.com/YannickJadoul/Parselmouth

**Comment by qiyoulu** [comment]
> The relevant place for this is probably actually on https://github.com/YannickJadoul/Parselmouth
