### ISSUE TITLE
interval contents search feature

### ISSUE THREAD

**Issue by mr-martian** [SwatPhonLab/UltraTrace#84]
_Originally posted by @jonorthwash at 2019-11-02T05:09:40Z ([original issue](https://github.swarthmore.edu/PhonLab/dicom-annotator/issues/84))_

Develop an interface to search the contents of TextGrid intervals and jump to any interval clicked on from among the results.

I imagine a pane on the right side of the interface, probably hidden by default (but a button to toggle its visibility, probably with a magnifying glass icon—the window should enlarge to contain it and reduce to current normal when it's gone).  A simple search interface is at the top.  The user specifies a tier name (from a dropdown list of all available) and a regex, and below the search interface, a list of all intervals matching that search is populated (probably not live, but on [Enter] in the regex box or click on the search button).

The intervals are listed one per line with the following details for each: the file in the project, the [non-empty?] interval number in the tier, and something like a concordance search (the matching text in bold / highlighted ± some number of surrounding characters or words).  Probably also some indication of the percentage of ultrasound frames in that interval that have been annotated.

When the item on the list is clicked, that file is opened, the interval is highlighted and selected, and the first frame of the interval is displayed as if it had been clicked on.  It might be nice to highlight other matching intervals in the same TextGrid somehow.

So this issue can be broken down into the following main tasks (potentially could be broken away into separate issues:
- [x] search interface (UI only)
- [x] function for identifying matching intervals
- [x] UI for results
- [x] functionality to jump to intervals upon clicking results

**Comment by mr-martian** [comment]
_Originally posted by @jonorthwash at 2019-11-02T05:26:53Z_

It might also be nice to be able to save searches.  Let's see how the basic functionality goes first, though, and then maybe we can make saving searches a new issue.

**Comment by mr-martian** [comment]
![Screenshot from 2019-11-13 21-41-59](https://user-images.githubusercontent.com/5350777/68822253-72be7b80-065e-11ea-8dc2-79560825ad0a.png)

Current search interface.

Clicking on any part of the displayed data will jump to the relevant interval and maximize it (roughly the same behavior as Command-N).

I tried to bind `<Enter>` in the search box, but it didn't work properly on Mac or Mint and would activate itself every 30 seconds or so on Debian.

Remaining TODOs:
- [ ] Highlight matching text
- [ ] Button to open search window (currently only accessible with Command/Alt-F)
 - Where should it be?
- [ ] Relationship to frames in result list

**Comment by BartholomaeusAstrum** [comment]
Crashes on regex search

```
Exception in Tkinter callback
Traceback (most recent call last):
  File "/usr/local/Cellar/python/3.7.4/Frameworks/Python.framework/Versions/3.7/lib/python3.7/tkinter/__init__.py", line 1705, in __call__
    return self.func(*args)
  File "/Users/nstern1/Desktop/UltraTrace/ultratrace/modules/search.py", line 69, in search
    pat = re.compile(self.regex.get(), re.IGNORECASE | re.MULTILINE | re.DOTALL)
NameError: name 're' is not defined
```

**Comment by keggsmurph21** [comment]
@BartholomaeusAstrum should be fixed in e4113de
