### ISSUE TITLE
Program exit on unknown error (something to do with traces?) EDIT: on mouse scroll

### ISSUE THREAD

**Issue by BartholomaeusAstrum** [SwatPhonLab/UltraTrace#96]
I was placing crosshairs on a frame and the program suddenly quit can gave the error below. It may have happened as I clicked to place the crosshair? Otherwise I am not sure what triggered the error. On restart everything seems to be behaving as normal.

```
Traceback (most recent call last):
  File "/usr/local/Cellar/python/3.7.4/Frameworks/Python.framework/Versions/3.7/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/local/Cellar/python/3.7.4/Frameworks/Python.framework/Versions/3.7/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/Users/nstern1/Desktop/UltraTrace/ultratrace/__main__.py", line 605, in <module>
    app.mainloop()
  File "/usr/local/Cellar/python/3.7.4/Frameworks/Python.framework/Versions/3.7/lib/python3.7/tkinter/__init__.py", line 1283, in mainloop
    self.tk.mainloop(n)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xff in position 0: invalid start byte
```

**Comment by BartholomaeusAstrum** [comment]
Same error occurred again, I think on mouse scroll while mouse was over the PNG.

```
Traceback (most recent call last):
  File "/usr/local/Cellar/python/3.7.4/Frameworks/Python.framework/Versions/3.7/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/local/Cellar/python/3.7.4/Frameworks/Python.framework/Versions/3.7/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/Users/nstern1/Desktop/UltraTrace/ultratrace/__main__.py", line 605, in <module>
    app.mainloop()
  File "/usr/local/Cellar/python/3.7.4/Frameworks/Python.framework/Versions/3.7/lib/python3.7/tkinter/__init__.py", line 1283, in mainloop
    self.tk.mainloop(n)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xff in position 0: invalid start byte
```

**Comment by BartholomaeusAstrum** [comment]
Program exits on scroll on Mac mouse trackpad.

**Comment by kmurphy4** [comment]
Yep, maybe best to wrap everything in a 
```python
while True:
    try:
        app.mainloop()
    except UnicodeDecodeError as e:
        error(e)
```
At least until we figure out the cause of this bug ....

**Comment by jonorthwash** [comment]
> Yep, maybe best to wrap everything in a

The problem with this approach is that now the program doesn't seem to close when closed by the user.  It has to be force-closed.

**Comment by keggsmurph21** [comment]
My suggestion would be to add a `break` after `app.mainloop()` in the `try`-body

**Comment by BartholomaeusAstrum** [comment]
This is fixed now, and I believe it was fixed by the recommendation made above. (I can't find the specific commit, unfortunately)

**Comment by keggsmurph21** [comment]
> This is fixed now, and I believe it was fixed by the recommendation made above. (I can't find the specific commit, unfortunately)

298d5ef8ddceb4741befe738fc868937364a03d2 (https://git-scm.com/docs/git-blame) :^)
